services:

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    networks:
      - node-red-mqtt-network
    volumes:
      - ./node_red_data:/data

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto 
    ports:
      - 1883:1883 # mqtt 
    volumes: 
      - ./mosquitto_config:/mosquitto/config
      - ./mosquitto_data:/mosquitto/data
      - ./mosquitto_log:/mosquitto/log
    networks:
      - node-red-mqtt-network 

  open-ssl:
    image: alpine/openssl:latest
    container_name: open-ssl
    working_dir: /root 
    volumes: 
      - ./open_ssl_root:/root 
    networks:
      - open-ssl-network 

  open-policy-agent:
    image: openpolicyagent/opa:latest 
    container_name: open-policy-agent
    ports:
      - 8181:8181 
    networks:
      - open-policy-agent-network
    

volumes:
  node_red_data:
  mosquitto_config: 
  mosquitto_data:
  mosquitto_log:
  open_ssl_root: 

networks:
  node-red-mqtt-network:
  open-ssl-network:
  open-policy-agent-network: 