services:

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    networks:
      - zero-trust-network
    volumes:
      - ./node_red_data:/data

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto 
    ports:
      - 1883:1883 # mqtt 
    volumes: 
      - ./mosquitto_config:/mosquitto/config
      - ./mosquitto_data:/mosquitto/data
      - ./mosquitto_log:/mosquitto/log
    networks:
      - zero-trust-network

  open-ssl:
    image: alpine/openssl:latest
    container_name: open-ssl
    entrypoint: "/bin/sh"
    command: /bin/sh "./scripts/generate_root_ca.sh"
    volumes: 
      - ./open_ssl_certs:/certs
      - ./open_ssl_scripts:/scripts
    networks:
      - zero-trust-network

volumes:
  node_red_data:
  mosquitto_config: 
  mosquitto_data:
  mosquitto_log:
  open_ssl_root: 

networks:
  zero-trust-network: 